import Head from 'next/head'

export default function Home({ info }) {
  const generalInfo = info.data 
  const statesInfo =  info.data.states

  return (
    <div className='px-4 font-sans'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className='px-2 py-4 text-3xl'>
          Covid Stats NG
        </div>

        <div className='grid grid-cols-1 gap-8 md:grid-cols-4'>
          {
            statesInfo.map((item) => (
              <div key={item._id} className='bg-white p-6 py-10 rounded-lg shadow-lg'>
                  <h4 className='text-2xl font-medium mb-3 text-green-700 '>
                    {item?.state}
                  </h4>
                  <p className='text-xl'>
                    Confirmed Cases: {' '} {item?.confirmedCases.toLocaleString()}
                  </p>
                  <p className='text-xl'>
                    Discharged Patients: {' '} {item?.discharged.toLocaleString()}
                  </p>
                  <p className='text-xl'>
                    Deaths: {' '} {item?.death.toLocaleString()}
                  </p>
              </div>
            )) 
          }
        </div>
      </div>

      <div className='my-3 py-2 border-black/50 border-t space-y-2 text-xl'>
        <p>
          Total Persons Tested in NG: {' '} 5,441,162
        </p>
        <p>
          Total Confirmed Cases: {' '} {generalInfo?.totalConfirmedCases.toLocaleString()}
        </p>
        <p>
          Total Active Cases: {' '} {generalInfo?.totalActiveCases.toLocaleString()}
        </p>
        <p>
          Total Persons Discharged: {' '} {generalInfo?.discharged.toLocaleString()}
        </p>
        <p>
          Total Deaths : {' '} {generalInfo?.death.toLocaleString()}
        </p>

      </div>

      
    </div>
  )
}

export async function getServerSideProps(ctx) {
  const info = await fetch('https://covidnigeria.herokuapp.com/api').then(res => res.json())

  return {
    props: {
      info,
    }
  } 
} 